import type { Metadata } from "next";
import { Montserrat} from "next/font/google";
import "./globals.css";


const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="apple-touch-icon" href="/apple-touch-icon.png" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="theme-color" content="#000000" />
        <meta name="description" content="Generated by create next app" />
        <meta name="og:title" content="Create Next App" />
        <meta name="og:description" content="Generated by create next app" />
        <meta name="og:image" content="/og.png" />
        <meta name="twitter:card" content="summary_large_image" />
        <meta name="twitter:title" content="Create Next App" />
        <meta name="twitter:description" content="Generated by create next app" />
        <meta name="twitter:image" content="/og.png" />
        <meta name="twitter:site" content="@vercel" />
        <meta name="twitter:creator" content="@vercel" />
      </head>
      <body
        className={`${montserrat.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
